<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\..\ev vegi projekt\F1ZoneSolution\F1ZoneLibrary\F1ZoneLibrary.csproj" />
    <ProjectReference Include="..\F1ZoneLibrary\F1ZoneLibrary.csproj" />
	<PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
	<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.20" />
	<PackageReference Include="System.ServiceModel.Syndication" Version="9.0.11" />
  </ItemGroup>

</Project>
